<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { adminUsers } from '../../mock/demoData.js'
import { useUiStore } from '../../stores/ui.js'

const router = useRouter(), { notify } = useUiStore()
const active = ref('users'), keyword = ref('')
const tabs = [['users','◉','用户管理'],['org','◇','组织与权限'],['roles','◆','角色管理'],['vehicle','▱','车型配置']]
const filteredUsers = computed(() => adminUsers.filter(user => Object.values(user).flat().join(' ').toLowerCase().includes(keyword.value.toLowerCase())))
function logout() { localStorage.removeItem('zhiku_token'); router.replace('/login') }
</script>

<template>
  <div class="admin"><aside class="admin-nav"><div class="brand"><img class="brand-mark" src="/logo.png"><div><strong>智库控制台</strong><small>Knowledge Console</small></div></div><nav class="admin-menu"><button v-for="tab in tabs" :key="tab[0]" class="admin-tab" :class="{ active: active === tab[0] }" @click="active = tab[0]">{{ tab[1] }} <span>{{ tab[2] }}</span></button></nav><button class="back-chat" @click="router.push('/chat')">← <span>返回问答</span></button><button class="back-chat logout" @click="logout">退出登录</button></aside>
    <main class="admin-main">
      <template v-if="active === 'users'"><div class="admin-header"><div><h1>用户管理</h1><p>统一管理企业用户、组织关系与问答权限</p></div><button class="primary-btn" @click="notify('企业用户同步完成')">同步企业用户</button></div><div class="stats"><div class="stat-card"><span>用户总数</span><strong>1,286</strong></div><div class="stat-card"><span>今日活跃</span><strong>238</strong></div><div class="stat-card"><span>已分配角色</span><strong>1,214</strong></div><div class="stat-card"><span>组织覆盖</span><strong>32</strong></div></div><section class="panel"><div class="panel-toolbar"><input v-model="keyword" class="search" placeholder="搜索姓名、账号或组织"><button class="ghost-btn">筛选权限</button></div><table class="admin-table"><thead><tr><th>用户</th><th>账号</th><th>组织</th><th>角色</th><th>权限</th><th>操作</th></tr></thead><tbody><tr v-for="user in filteredUsers" :key="user.account"><td><div class="user-cell"><span class="user-avatar">{{ user.name[0] }}</span>{{ user.name }}</div></td><td>{{ user.account }}</td><td>{{ user.org }}</td><td>{{ user.role }}</td><td><span v-for="permission in user.permissions" :key="permission" class="tag">{{ permission }}</span></td><td><button class="tiny-action" @click="notify('已打开用户权限编辑')">编辑</button></td></tr></tbody></table></section></template>
      <template v-else-if="active === 'org'"><div class="admin-header"><div><h1>组织与权限</h1><p>查看组织树，并配置部门级知识问答权限</p></div><button class="primary-btn" @click="notify('组织数据增量同步完成')">增量同步</button></div><section class="panel org-layout"><div class="tree"><div class="tree-item active">▾ 广汽集团</div><div class="tree-item indent">▾ 数字化中心</div><div class="tree-item indent">　 智能平台部</div><div class="tree-item indent">　 数据产品部</div><div class="tree-item indent">▸ 研究院</div><div class="tree-item indent">▸ 市场洞察部</div></div><div class="detail"><h2>数字化中心</h2><p class="muted">成员 236 人 · 4 个下级组织</p><h3>部门权限</h3><p><span class="tag">问答-技术</span><span class="tag">问答-竞品</span><span class="tag green">智能问数</span></p><button class="ghost-btn" @click="notify('部门权限已更新')">配置权限</button></div></section></template>
      <template v-else-if="active === 'roles'"><div class="admin-header"><div><h1>角色管理</h1><p>按岗位职责组合权限，降低批量授权成本</p></div><button class="primary-btn" @click="notify('已创建演示角色')">新建角色</button></div><section class="panel"><div class="role-grid"><article v-for="role in [['系统管理员','拥有平台全部配置和管理权限','全部权限'],['部门管理员','可管理本部门成员及授权','用户管理'],['数据分析师','可使用竞品分析和智能问数','问答-竞品'],['产品经理','技术、政策与竞品知识查询','问答-技术'],['普通用户','基础汽车知识问答权限','基础问答'],['访客','仅可浏览公开知识内容','只读']]" :key="role[0]" class="role-card"><h3>{{ role[0] }}</h3><p>{{ role[1] }}</p><span class="tag">{{ role[2] }}</span><div><button class="tiny-action" @click="notify('已打开角色编辑')">编辑角色</button></div></article></div></section></template>
      <template v-else><div class="admin-header"><div><h1>车型配置</h1><p>维护竞品分析使用的品牌、车系与数据口径</p></div><button class="primary-btn" @click="notify('车型配置已保存')">保存配置</button></div><section class="panel"><form class="vehicle-form" @submit.prevent="notify('车型配置已保存')"><label class="field"><span>品牌</span><select><option>广汽埃安</option><option>小鹏汽车</option></select></label><label class="field"><span>车系</span><select><option>AION RT</option><option>AION S</option></select></label><label class="field"><span>竞品品牌</span><select><option>小鹏汽车</option><option>比亚迪</option></select></label><label class="field"><span>竞品车系</span><select><option>MONA M03</option><option>秦 PLUS EV</option></select></label><label class="field"><span>数据更新时间</span><input value="每日 02:00 自动更新"></label><label class="field"><span>默认分析周期</span><select><option>近 6 个月</option><option>近 12 个月</option></select></label></form></section></template>
    </main>
  </div>
</template>
